// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDefaultExercises(ctx context.Context, username string) error
	AddExerciseToWorkout(ctx context.Context, arg AddExerciseToWorkoutParams) (WorkoutExercise, error)
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	DeleteExercise(ctx context.Context, arg DeleteExerciseParams) error
	DeleteExerciseInWE(ctx context.Context, arg DeleteExerciseInWEParams) error
	DeleteExerciseInWorkoutWE(ctx context.Context, arg DeleteExerciseInWorkoutWEParams) error
	DeleteUser(ctx context.Context, username string) error
	DeleteUserExercises(ctx context.Context, username string) error
	DeleteUserMacros(ctx context.Context, username string) error
	DeleteUserTrack(ctx context.Context, username string) error
	DeleteUserTrackWorkouts(ctx context.Context, username string) error
	DeleteUserWorkoutExercises(ctx context.Context, username string) error
	DeleteUserWorkoutRecord(ctx context.Context, utwID int64) error
	DeleteUserWorkouts(ctx context.Context, username string) error
	DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error
	DeleteWorkoutInWE(ctx context.Context, arg DeleteWorkoutInWEParams) error
	GetDietDetails(ctx context.Context, username string) (GetDietDetailsRow, error)
	GetExercise(ctx context.Context, exerID int64) (Exercise, error)
	GetExercises(ctx context.Context, arg GetExercisesParams) ([]Exercise, error)
	GetFitnessDetails(ctx context.Context, username string) (GetFitnessDetailsRow, error)
	GetMacroByDate(ctx context.Context, arg GetMacroByDateParams) ([]UserMacro, error)
	GetMacros(ctx context.Context, arg GetMacrosParams) ([]UserMacro, error)
	GetRecord(ctx context.Context, utwID int64) (string, error)
	GetRecords(ctx context.Context, arg GetRecordsParams) ([]GetRecordsRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserTrack(ctx context.Context, arg GetUserTrackParams) ([]GetUserTrackRow, error)
	GetWorkout(ctx context.Context, workoutID int64) (Workout, error)
	GetWorkoutExercises(ctx context.Context, arg GetWorkoutExercisesParams) ([]GetWorkoutExercisesRow, error)
	GetWorkouts(ctx context.Context, arg GetWorkoutsParams) ([]Workout, error)
	RecordDetails(ctx context.Context, arg RecordDetailsParams) (UserDetail, error)
	RecordMacros(ctx context.Context, arg RecordMacrosParams) (UserMacro, error)
	RecordUserTrack(ctx context.Context, arg RecordUserTrackParams) (UserTrack, error)
	RecordWorkout(ctx context.Context, arg RecordWorkoutParams) (UserTrackWorkout, error)
	UpdateHeight(ctx context.Context, arg UpdateHeightParams) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateWeight(ctx context.Context, arg UpdateWeightParams) (User, error)
}

var _ Querier = (*Queries)(nil)
