// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddDefaultExercises(ctx context.Context, username string) error
	AddExerciseToWorkout(ctx context.Context, arg AddExerciseToWorkoutParams) (WorkoutExercise, error)
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	DeleteExercise(ctx context.Context, username string) error
	DeleteUser(ctx context.Context, username string) error
	DeleteUserMacros(ctx context.Context, username string) error
	DeleteUserTrack(ctx context.Context, username string) error
	DeleteUserTrackWorkouts(ctx context.Context, username string) error
	DeleteWorkoutExercises(ctx context.Context, username string) error
	DeleteWorkouts(ctx context.Context, username string) error
	GetExercises(ctx context.Context, arg GetExercisesParams) ([]Exercise, error)
	GetMacro(ctx context.Context, arg GetMacroParams) (UserMacro, error)
	GetMacros(ctx context.Context, arg GetMacrosParams) ([]UserMacro, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserTrack(ctx context.Context, arg GetUserTrackParams) ([]UserTrack, error)
	GetWorkoutExercises(ctx context.Context, arg GetWorkoutExercisesParams) ([]GetWorkoutExercisesRow, error)
	GetWorkouts(ctx context.Context, arg GetWorkoutsParams) ([]Workout, error)
	RecordMacros(ctx context.Context, arg RecordMacrosParams) (UserMacro, error)
	RecordUserTrack(ctx context.Context, arg RecordUserTrackParams) (UserTrack, error)
	RecordWorkout(ctx context.Context, arg RecordWorkoutParams) (UserTrackWorkout, error)
	UpdateHeight(ctx context.Context, arg UpdateHeightParams) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateWeight(ctx context.Context, arg UpdateWeightParams) (User, error)
}

var _ Querier = (*Queries)(nil)
